src/PaperSource.AspNetCoreAuthorization/Models/LoginViewModel.cs
namespace PaperSource.AspNetCoreAuthorization.Models
{
    public class LoginViewModel
    {
        
    }
}

src/PaperSource.AspNetCoreAuthorization/Models/Order.cs
namespace PaperSource.AspNetCoreAuthorization.Models
{
    public class Order
    {
        public int Id { get; set; }
    }
}

src/PaperSource.AspNetCoreAuthorization/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PaperSource.AspNetCoreAuthorization.Models;

namespace PaperSource.AspNetCoreAuthorization.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger _logger;

        public HomeController(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<HomeController>();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel vm, string returnUrl = null)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, "Fake User"),
                new Claim("age", "25", ClaimValueTypes.Integer),
                new Claim("permission-foo", "grant")
            };

            var identity = new ClaimsIdentity("MyCookieMiddlewareInstance");
            identity.AddClaims(claims);

            var principal = new ClaimsPrincipal(identity);

            await HttpContext.Authentication.SignInAsync("MyCookieMiddlewareInstance",
                principal,
                new AuthenticationProperties
                {
                    ExpiresUtc = DateTime.UtcNow.AddMinutes(20)
                });

            _logger.LogInformation(4, "User logged in.");

            return RedirectToLocal(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await HttpContext.Authentication.SignOutAsync("MyCookieMiddlewareInstance");

            _logger.LogInformation(4, "User logged out.");

            return RedirectToAction(nameof(Index));
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }
    }
}

src/PaperSource.AspNetCoreAuthorization/Controllers/PermissionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PaperSource.AspNetCoreAuthorization.Services.Permissions;

namespace PaperSource.AspNetCoreAuthorization.Controllers
{
    public class PermissionController : Controller
    {
        [TypeFilter(typeof(PermissionFilterV1),
            Arguments = new object[] { new[] { Permission.Foo, Permission.Bar } })]
        public IActionResult ExampleV1()
        {
            return View("OK");
        }

        [AuthorizePermission(Permission.Foo, Permission.Bar)]
        [Authorize(Policy = "age-adult-policy")]
        public IActionResult ExampleV2()
        {
            return View("OK");
        }
    }
}

src/PaperSource.AspNetCoreAuthorization/Controllers/PolicyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PaperSource.AspNetCoreAuthorization.Controllers
{
    public class PolicyController : Controller
    {
        [Authorize(Policy = "age-adult-policy")]
        public IActionResult Allow()
        {
            return View("OK");
        }

        [Authorize(Policy = "age-elder-policy")]
        public IActionResult Deny()
        {
            return View("OK");
        }
    }
}

src/PaperSource.AspNetCoreAuthorization/Controllers/ResourceController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PaperSource.AspNetCoreAuthorization.Models;
using PaperSource.AspNetCoreAuthorization.Services.Resources;

namespace PaperSource.AspNetCoreAuthorization.Controllers
{
    public class ResourceController : Controller
    {
        IAuthorizationService _authorizationService;

        public ResourceController(IAuthorizationService authorizationService)
        {
            _authorizationService = authorizationService;
        }

        public async Task<IActionResult> ExampleV1(int id)
        {
            Order order = new Order(); //get resourse from DB

            if (await _authorizationService.AuthorizeAsync(this.User, order, "resource-allow-policy"))
            {
                return View("OK");
            }

            return new ChallengeResult(); //it produces 401 or 403 response (depending on user state)
        }

        public async Task<IActionResult> ExampleV2()
        {
            var requirements = new [] { Operations.Create, Operations.Read, Operations.Update };

            if (await _authorizationService.AuthorizeAsync(this.User, new Order(), requirements))
            {
                return View("OK");
            }

            return new ChallengeResult();  //it produces 401 or 403 response (depending on user state)
        }
    }
}

src/PaperSource.AspNetCoreAuthorization/Views/Home/Index.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Home Page";
}
<br />

<div class="row">
    <div class="col-sm-2">
        <h4>Policy-based: </h4>
    </div>
    <div class="col-sm-2 h4">
        @Html.ActionLink("Allow", "Allow", "Policy")
    </div>
    <div class="col-sm-2 h4">
    </div>
    <div class="col-sm-2 h4">
        @Html.ActionLink("Deny", "Deny", "Policy")
    </div>
</div>

<div class="row">
    <div class="col-sm-2">
        <h4>Resource-based: </h4>
    </div>
    <div class="col-sm-2 h4">
        @Html.ActionLink("ExampleV1 (Allow)", "ExampleV1", "Resource")
    </div>
    <div class="col-sm-2 h4">
        @Html.ActionLink("ExampleV2 (Allow)", "ExampleV2", "Resource")
    </div>
    <div class="col-sm-2 h4">
    </div>
</div>

<div class="row">
    <div class="col-sm-2">
        <h4>Permission-based: </h4>
    </div>
    <div class="col-sm-2 h4">
        @Html.ActionLink("ExampleV1 (Allow)", "ExampleV1", "Permission")
    </div>
    <div class="col-sm-2 h4">
        @Html.ActionLink("ExampleV2 (Allow)", "ExampleV2", "Permission")
    </div>
    <div class="col-sm-2 h4">
    </div>
</div>

<br/>
<br/>

<h4>User's claims:</h4>
@foreach (Claim claim in User.Claims)
{
    <b>@claim.Type:</b> @claim.Value    <br />
}

src/PaperSource.AspNetCoreAuthorization/Views/Home/Login.cshtml
@model PaperSource.AspNetCoreAuthorization.Models.LoginViewModel

@{
    ViewData["Title"] = "Log in";
}

<h2>@ViewData["Title"].</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            <form asp-controller="Home" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                <h4 style="color: green">TODO: username/password fields, external login provider buttons</h4>
                <hr />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default">Log in</button>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>

src/PaperSource.AspNetCoreAuthorization/Views/Shared/AccessDenied.cshtml
@{
    Layout = "_Layout";
}

<h2 style="color:red">Access denied!</h2>

src/PaperSource.AspNetCoreAuthorization/Views/Shared/OK.cshtml
@{
    Layout = "_Layout";
}

<h2 style="color:forestgreen">Success!</h2>

src/PaperSource.AspNetCoreAuthorization/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PaperSource.AspNetCoreAuthorization</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-brand">Logged as: @User.Identity.Name</div>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Html.PartialAsync("_LoginPartial")
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>